{
    'name': 'Accounts Extended',
    'version': '1.0',
    'category': 'Accounting',
    'description': """ 
        Extended functionality of Accounts for Ekara""",
    'author': 'NITS',
    'website': 'https://www.navabrindsol.com/',
    'depends': [
        'base',
        'account',
        'account_accountant',
        'analytic',
        'sale',
        'l10n_in',
        'l10n_in_reports_gstr',
        'hr_expense_extended',
        'payment',
        'account_budget',
        'multi_level_approval',
        'report_xlsx',
        'odoo_print_cheque',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/res_groups.xml',
        'data/budget_sequence.xml',
        'data/mail_template.xml',
        'wizard/account_report_view.xml',
        'wizard/budget_revision_reason_view.xml',
        'wizard/crr_report_view.xml',
        'wizard/cur_report_view.xml',
        'wizard/account_payment_register_views.xml',
        'report/reports.xml',
        'report/proforma_invoice.xml',
        'views/res_config_settings.xml',
        'views/crossoverd_budget.xml',
        'views/account_move.xml',
        'views/account_payment.xml',
        'views/cash_management.xml',
    ],
    'license': 'LGPL-3',

}
