{
    'name': "HR Extended",

    'description': """
        HR Extended Functionality for Ekara
        
    """,
    'category': 'HR',
    'version': '17.1',
    'depends': [
        'base',
        'mail',
        'contacts',
        'hr',
        'hr_recruitment',
        'hr_recruitment_extract',
        'account',
        'product',
        'sale',
        'project',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'report/pre_emp_check_report.xml',
        'report/employee_indent_report.xml',
        'report/salary_breakup_report.xml',
        'report/nda_form.xml',
        'report/external_media_communication_declare.xml',
        'report/employee_verification_form.xml',
        'report/criminal_case_report.xml',
        'report/consent_form.xml',
        'report/code_of_conduct.xml',
        'report/appointment_order_form.xml',
        'report/interview_assessment.xml',
        'report/bgv_email_template_data.xml',
        'report/pf_nomination_form.xml',
        'data/sequence.xml',
        'data/job_levels_demo.xml',
        'data/mail_template_data.xml',
        'wizard/mail_activity_schedule_views.xml',
        'views/hr_config.xml',       
        'views/recruitment_config.xml',        
        'views/employee_indent_view.xml',
        'views/applicant_recruitment_invitation.xml',
        'views/pre_emp_check.xml',
        'views/interview_assessment.xml',
        'views/kra_master.xml',
        'views/join_doc_config.xml',
        'views/joining_documents.xml',
        'views/employee_kra.xml',
        'views/hr_employee.xml',
        'views/hr_applicant.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
