{
    'name': 'Employee Appraisal Integration',
    'version': '17.0',
    'category': 'Human Resources',
    'summary': 'Integrate custom employee fields with the hr_appraisal module.',

    'author': 'Your Company',
    'depends': [
        'base',
        'hr',
        'hr_appraisal',
        'report_xlsx',
        'hr_extended',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/increment_letter.xml',
        'data/appraisal_letter_data.xml',
        'data/annual_increment_promotion_letter.xml',
        'data/increment_redesignation_letter_iim_job_approved.xml',
        'views/hr_appraisal.xml',
        'reports/360_performance_review.xml',
        'reports/360_performance_review_excel.xml',
        'reports/performance_review.xml',
        'reports/director_final_ratings.xml',
        'reports/performance_impvmt.xml',
        'reports/annual_performance_review.xml',
        'reports/review_performance.xml',
        'views/self_rating.xml',
        'views/hr_pip.xml',
        'views/performance_review_form.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
